name: 每小时运行 Colab_rank_gn.py 脚本并更新 HTML

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次（UTC）
  workflow_dispatch:      # 可手动触发

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 使用适合的 Python 版本

      - name: 安装 Python 依赖
        run: |
          pip install -r requirements.txt || true  # 如果有 requirements.txt 文件，安装依赖

      - name: 运行 Python 脚本生成 HTML
        run: python Colab_rank_gn.py  # 运行你的 Python 脚本

      - name: 提交并推送 index.html 到 GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "自动更新 index.html at $(date)" || echo "No changes to commit"
          git push
