name: 每半小时运行脚本并更新HTML

on:
  schedule:
    - cron: '*/30 1-8 * * 1-5'  # 每小时运行一次（UTC）
  workflow_dispatch:      # 可手动触发

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 使用适合的 Python 版本

      - name: 安装 Python 依赖
        run: |
          pip install -r requirements.txt || true  # 如果有 requirements.txt 文件，安装依赖

      - name: 安装 Playwright 和浏览器驱动
        run: |
          pip install playwright
          python -m playwright install chromium --with-deps  # 安装 Chromium 浏览器驱动

      - name: 运行 Python 脚本生成 HTML
        run: python colab_rank_gn.py  # 运行你的 Python 脚本

      - name: 提交并推送 index.html 到 GitHub Pages
        run: |
          git config --global user.name "javboxes"
          git config --global user.email "emma_wl@hotmail.com"
          git add index.html
          git commit -m "Update index.html from GitHub Actions" || echo "No changes"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
